var searchData=
[
  ['pack_0',['Downloading QP/C as a CMSIS-Pack',['../gs_get.html#gs_pack',1,'']]],
  ['parameters_1',['Event Parameters',['../srs-qp_evt.html#srs-qp_evt-par',1,'']]],
  ['party_20code_2',['Third-Party Code',['../exa.html#exa_sec_3rd',1,'']]],
  ['party_20kernels_3',['3rd-Party Kernels',['../index.html#over_3rd-party',1,'']]],
  ['party_20middleware_4',['Examples for 3rd-party Middleware',['../exa.html#exa_middleware',1,'']]],
  ['party_20rtos_5',['Ports to Third-Party RTOS',['../ports_rtos.html',1,'ports']]],
  ['party_20rtos_6',['Examples for 3rd-party RTOS',['../exa.html#exa_rtos',1,'']]],
  ['pc_20lint_20plus_7',['PC-Lint-Plus',['../ports_lint.html',1,'ports']]],
  ['pc_20lint_20plus_20options_20for_20qp_20c_8',['Structure of PC-Lint-Plus Options for QP/C',['../ports_lint.html#lint_options',1,'']]],
  ['philosophers_20problem_20dpp_9',['Dining Philosophers Problem (DPP)',['../tut_dpp.html',1,'gs_tut']]],
  ['plus_10',['PC-Lint-Plus',['../ports_lint.html',1,'ports']]],
  ['plus_20options_20for_20qp_20c_11',['Structure of PC-Lint-Plus Options for QP/C',['../ports_lint.html#lint_options',1,'']]],
  ['poolnum_5f_12',['poolNum_',['../struct_q_evt.html#afd38e6cf51d31fce9c7d7d2b48a6057e',1,'QEvt']]],
  ['pools_13',['Event Pools',['../srs-qp_emm.html#srs-qp_emm-pools',1,'']]],
  ['popularity_20amp_20maturity_14',['Popularity &amp;amp; Maturity',['../index.html#over_popular',1,'']]],
  ['port_15',['Port',['../uc-os2.html#uc-os2_exa',1,'Examples for the uC-OS2 Port'],['../embos.html#embos_build',1,'QP/C Source Files Needed in this QP/C Port'],['../threadx.html#threadx_build',1,'QP/C Source Files Needed in this QP/C Port']]],
  ['port_16',['Examples for the Zephyr port',['../zephyr.html#zephyr_exa',1,'']]],
  ['port_20to_20freertos_17',['About the QP/C Port to FreeRTOS',['../freertos.html#freertos_about',1,'']]],
  ['port_20to_20uc_20os2_18',['About the QP/C Port to uC-OS2',['../uc-os2.html#uc-os2_about',1,'']]],
  ['port_20to_20zephyr_19',['About the QP/C Port to Zephyr',['../zephyr.html#zephyr_about',1,'']]],
  ['portability_20',['Portability',['../srs-qp_nf.html#srs-qp_nf-port',1,'']]],
  ['portability_20amp_20configurability_21',['Portability &amp;amp; Configurability',['../srs-qp_over.html#srs-qp_over-conf',1,'']]],
  ['ports_22',['Ports',['../ports.html',1,'Ports'],['../uc-os2.html#uc-os2_source',1,'uC-OS2 Source and ARM Cortex-M3/M4 Ports']]],
  ['ports_20built_20in_20kernels_23',['Native Ports (Built-in Kernels)',['../ports_native.html',1,'ports']]],
  ['ports_20to_20arm_20cortex_20m_24',['Interrupts in the QP/C Ports to ARM Cortex-M',['../arm-cm.html#arm-cm_int',1,'']]],
  ['ports_20to_20general_20purpose_20oses_25',['Ports to General-Purpose OSes',['../ports_gpos.html',1,'ports']]],
  ['ports_20to_20third_20party_20rtos_26',['Ports to Third-Party RTOS',['../ports_rtos.html',1,'ports']]],
  ['posix_20multithreaded_27',['POSIX (Multithreaded)',['../posix.html',1,'ports_gpos']]],
  ['posix_20qv_20single_20threaded_28',['POSIX-QV (Single Threaded)',['../posix-qv.html',1,'ports_gpos']]],
  ['posting_29',['Direct Event Posting',['../srs-qp_edm.html#srs-qp_edm-post',1,'']]],
  ['power_20architecture_30',['Low Power Architecture',['../srs-qp_ao.html#srs-qp_ao-power',1,'']]],
  ['power_20code_31',['The Low-Power Code',['../tut_low.html#tut_low-code',1,'']]],
  ['power_20efficiency_32',['Power Efficiency',['../srs-qp_tm.html#srs-qp_tm-power',1,'']]],
  ['power_20example_33',['Low-Power Example',['../tut_low.html',1,'gs_tut']]],
  ['predefined_20trace_20records_34',['Predefined Trace Records',['../srs-qp_qs.html#srs-qp_qs-pre',1,'']]],
  ['preemption_20threshold_20scheduling_35',['Preemption-Threshold Scheduling',['../srs-qp_qk.html#srs-qp_qk-pts',1,'']]],
  ['preemptions_20in_20qk_36',['Preemptions in %QK',['../srs-qp_qk.html#srs-qp_qk-pre',1,'']]],
  ['preemptive_20dual_20mode_20kernel_37',['Preemptive Dual-Mode Kernel',['../srs-qp_qxk.html',1,'srs-qp']]],
  ['preemptive_20dual_20mode_20qxk_20kernel_38',['Preemptive &quot;Dual-Mode&quot; QXK Kernel',['../arm-cm_qxk.html',1,'arm-cm']]],
  ['preemptive_20kernel_39',['Preemptive Kernel',['../srs-qp_qv.html',1,'Non-Preemptive Kernel'],['../srs-qp_qv.html#srs-qp_qv-def',1,'QV Non-Preemptive Kernel']]],
  ['preemptive_20kernel_40',['QV (Non-preemptive Kernel)',['../api.html#api_qv',1,'']]],
  ['preemptive_20non_20blocking_20kernel_41',['Preemptive Non Blocking Kernel',['../srs-qp_qk.html',1,'Preemptive Non-Blocking Kernel'],['../srs-qp_qk.html#srs-qp_qk-def',1,'QK Preemptive Non-Blocking Kernel']]],
  ['preemptive_20non_20blocking_20qk_20kernel_42',['Preemptive Non-Blocking QK Kernel',['../arm-cm_qk.html',1,'arm-cm']]],
  ['preemptive_20qv_20kernel_43',['Non-preemptive QV Kernel',['../arm-cm_qv.html',1,'arm-cm']]],
  ['preemptive_20rtc_20kernel_44',['QK (Preemptive RTC Kernel)',['../api.html#api_qk',1,'']]],
  ['principle_45',['Shared-Nothing Principle',['../srs-qp_ao.html#srs-qp_ao-sharing',1,'']]],
  ['prio_46',['prio',['../struct_q_active.html#acc0b27a6740f03639727be452f1e6b83',1,'QActive']]],
  ['priority_47',['Priority',['../srs-qp_ao.html#srs-qp_ao-prio',1,'']]],
  ['problem_20dpp_48',['Dining Philosophers Problem (DPP)',['../tut_dpp.html',1,'gs_tut']]],
  ['processing_49',['Run To Completion (RTC) Processing',['../srs-qp_sm.html#srs-qp_sm-rtc',1,'']]],
  ['processing_20in_20qk_50',['Idle Processing in QK',['../srs-qp_qk.html#srs-qp_qk-idle',1,'']]],
  ['processing_20in_20qv_51',['Idle Processing in QV',['../srs-qp_qv.html#srs-qp_qv-idle',1,'']]],
  ['processor_52',['State Machine Processor',['../srs-qp_sm.html#srs-qp_sm-proc',1,'']]],
  ['projects_53',['Projects',['../index.html#over_closed-source',1,'Closed Source Projects'],['../exa.html#exa_own',1,'Creating your Own QP/C Projects'],['../index.html#over_open-source',1,'Open Source Projects']]],
  ['protocol_54',['Data Protocol',['../srs-qp_qs.html#srs-qp_qs-proto',1,'']]],
  ['pthre_55',['pthre',['../struct_q_active.html#afa3b46e6f8caec240fa3292121e74535',1,'QActive']]],
  ['publish_20subscribe_56',['Publish-Subscribe',['../srs-qp_edm.html#srs-qp_edm-ps',1,'']]],
  ['purpose_20and_20scope_57',['Purpose and Scope',['../srs-qp.html#srs-qp_scope',1,'Purpose and Scope'],['../sas-qp.html#sas-qp_scope',1,'Purpose and Scope'],['../sds-qp.html#sds-qp_scope',1,'Purpose and Scope']]],
  ['purpose_20oses_58',['Ports to General-Purpose OSes',['../ports_gpos.html',1,'ports']]]
];
