var searchData=
[
  ['ease_20of_20development_0',['Ease of Development',['../srs-qp_nf.html#srs-qp_nf-develop',1,'']]],
  ['editions_1',['QP Framework Editions',['../index.html#over_ed',1,'']]],
  ['efficiency_2',['Efficiency',['../srs-qp_tm.html#srs-qp_tm-power',1,'Power Efficiency'],['../index.html#over_eff',1,'Size and Efficiency']]],
  ['embos_3',['embOS',['../embos.html',1,'ports_rtos']]],
  ['encapsulation_20for_20concurrency_4',['Encapsulation for Concurrency',['../srs-qp_ao.html#srs-qp_ao-enc',1,'']]],
  ['end_5',['end',['../struct_q_e_queue.html#a3c6fb10fbe468edb5975d8b6b9df00ba',1,'QEQueue::end'],['../struct_q_m_pool.html#a15687bf7a7ddc3e78a102db40bf5c5d5',1,'QMPool::end']]],
  ['entryaction_6',['entryAction',['../struct_q_m_state.html#a7f20fb69b982f91c143a22d29e51ab55',1,'QMState']]],
  ['enum_5ft_7',['enum_t',['../qp_8h.html#ad11e2d4dff3c15b0b5f9a13a47c7fb1a',1,'qp.h']]],
  ['epool_5f_8',['ePool_',['../struct_q_f___attr.html#ac46c714bfe195bf249e65b0a1dcbf461',1,'QF_Attr']]],
  ['equeue_9',['eQueue',['../struct_q_active.html#a868d532829e38dfe94b3a0593b9861eb',1,'QActive']]],
  ['event_10',['Event',['../srs-qp_ao.html#srs-qp_ao-curr',1,'Current Event'],['../srs-qp_sm.html#srs-qp_sm-evt',1,'Current Event']]],
  ['event_20delivery_20mechanisms_11',['Event Delivery Mechanisms',['../srs-qp_edm.html',1,'srs-qp']]],
  ['event_20exchange_20view_12',['Event Exchange View',['../sds-qp_inter.html#sds-qp_inter-evt',1,'']]],
  ['event_20management_13',['Event Management',['../api.html#api_mut',1,'Mutable Event Management'],['../srs-qp_emm.html#srs-qp_emm-zero',1,'Zero-Copy Event Management']]],
  ['event_20memory_20management_14',['Event Memory Management',['../srs-qp_emm.html',1,'srs-qp']]],
  ['event_20ownership_20rules_15',['Mutable Event Ownership Rules',['../srs-qp_emm.html#srs-qp_emm-ownership',1,'']]],
  ['event_20parameters_16',['Event Parameters',['../srs-qp_evt.html#srs-qp_evt-par',1,'']]],
  ['event_20pools_17',['Event Pools',['../srs-qp_emm.html#srs-qp_emm-pools',1,'']]],
  ['event_20posting_18',['Direct Event Posting',['../srs-qp_edm.html#srs-qp_edm-post',1,'']]],
  ['event_20queue_19',['Event Queue',['../srs-qp_ao.html#srs-qp_ao-queue',1,'']]],
  ['event_20queues_20raw_20thread_20safe_20',['Event Queues (raw thread-safe)',['../api.html#api_queue',1,'']]],
  ['event_20recycling_21',['Automatic Event Recycling',['../srs-qp_emm.html#srs-qp_emm-gc',1,'']]],
  ['event_20signal_22',['Event Signal',['../srs-qp_evt.html#srs-qp_evt-sig',1,'']]],
  ['events_23',['Events',['../srs-qp_evt.html',1,'Events'],['../api.html#api_evt',1,'Events'],['../srs-qp_emm.html#srs-qp_emm-imm',1,'Immutable Events'],['../srs-qp_emm.html#srs-qp_emm-mut',1,'Mutable Events'],['../srs-qp_tm.html#srs-qp_tm-te',1,'Time Events']]],
  ['events_20to_20a_20state_20machine_24',['Dispatching Events to a State Machine',['../srs-qp_sm.html#srs-qp_sm-dispatch',1,'']]],
  ['example_25',['Low-Power Example',['../tut_low.html',1,'gs_tut']]],
  ['example_20applications_26',['Example Applications',['../exa.html#exa_sec_apps',1,'']]],
  ['example_20code_27',['Example Code',['../freertos.html#freertos_exa',1,'']]],
  ['example_20code_20organization_28',['Example Code Organization',['../exa.html#exa_code',1,'']]],
  ['examples_29',['Examples',['../exa.html',1,'Examples'],['../exa.html#exa_native',1,'Native Examples']]],
  ['examples_20for_203rd_20party_20middleware_30',['Examples for 3rd-party Middleware',['../exa.html#exa_middleware',1,'']]],
  ['examples_20for_203rd_20party_20rtos_31',['Examples for 3rd-party RTOS',['../exa.html#exa_rtos',1,'']]],
  ['examples_20for_20gpos_32',['Examples for GPOS',['../exa.html#exa_gpos',1,'']]],
  ['examples_20for_20qutest_33',['Examples for QUTest',['../exa.html#exa_qutest',1,'']]],
  ['examples_20for_20qwin_20gui_34',['Examples for QWin-GUI',['../exa.html#exa_qwin',1,'']]],
  ['examples_20for_20the_20uc_20os2_20port_35',['Examples for the uC-OS2 Port',['../uc-os2.html#uc-os2_exa',1,'']]],
  ['examples_20for_20the_20zephyr_20port_36',['Examples for the Zephyr port',['../zephyr.html#zephyr_exa',1,'']]],
  ['exchange_20view_37',['Event Exchange View',['../sds-qp_inter.html#sds-qp_inter-evt',1,'']]],
  ['execution_20context_38',['Execution Context',['../srs-qp_ao.html#srs-qp_ao-exec',1,'']]],
  ['exitaction_39',['exitAction',['../struct_q_m_state.html#ac0f5460022fba3a90d46c885e0b95957',1,'QMState']]],
  ['extended_20tasks_40',['Extended tasks',['../srs-qp_qxk.html#srs-qp_qxk-ext',1,'']]]
];
