var searchData=
[
  ['obj_0',['obj',['../union_q_asm_attr.html#ae52a13d64bb5d71c2ea05e132b65eb76',1,'QAsmAttr']]],
  ['object_20model_20of_20computation_1',['Active Object Model of Computation',['../srs-qp_ao.html#srs-qp_ao-model',1,'']]],
  ['object_20orientation_2',['Object Orientation',['../index.html#over_oop',1,'']]],
  ['object_20osal_3',['Active Object OSAL',['../sds-qp_ifc.html#sds-qp_osal-ao',1,'']]],
  ['objects_4',['Objects',['../srs-qp_ao.html',1,'Active Objects'],['../srs-qp_ao.html#srs-qp_ao-def',1,'Active Objects'],['../api.html#api_ao',1,'Active Objects'],['../srs-qp_qs.html#srs-qp_qs-ao',1,'Software Tracing &amp;amp; Active Objects']]],
  ['oct_2009_202009_5',['Version 4.1.00, Oct 09, 2009',['../history.html#qpc_4_1_00',1,'']]],
  ['of_20computation_6',['Active Object Model of Computation',['../srs-qp_ao.html#srs-qp_ao-model',1,'']]],
  ['of_20control_7',['of Control',['../srs-qp_over.html#srs-qp_over_inv',1,'Inversion of Control'],['../srs-qp_ao.html#srs-qp_ao-inv',1,'Inversion of Control']]],
  ['of_20development_8',['Ease of Development',['../srs-qp_nf.html#srs-qp_nf-develop',1,'']]],
  ['of_20interest_9',['Quickly Locating a Topic of Interest',['../help.html#help_random',1,'']]],
  ['of_20may_10',['Use of &quot;may&quot;',['../srs-qp.html#srs-qp_conv-may',1,'']]],
  ['of_20pc_20lint_20plus_20options_20for_20qp_20c_11',['Structure of PC-Lint-Plus Options for QP/C',['../ports_lint.html#lint_options',1,'']]],
  ['of_20shall_12',['Use of &quot;shall&quot;',['../srs-qp.html#srs-qp_conv-shall',1,'']]],
  ['of_20shall_20not_13',['Use of &quot;shall not&quot;',['../srs-qp.html#srs-qp_conv-shall-not',1,'']]],
  ['of_20should_14',['Use of &quot;should&quot;',['../srs-qp.html#srs-qp_conv-should',1,'']]],
  ['of_20use_15',['Context of Use',['../srs-qp_over.html#srs-qp_over-ctxt',1,'']]],
  ['on_20github_16',['Spexygen on GitHub',['../help.html#hel_spexygen',1,'']]],
  ['online_20help_17',['Using Online Help',['../help.html',1,'']]],
  ['online_20help_20sequentially_18',['Reading Online Help Sequentially',['../help.html#help_seq',1,'']]],
  ['open_20source_20projects_19',['Open Source Projects',['../index.html#over_open-source',1,'']]],
  ['option_20file_20',['option file',['../ports_lint.html#lint_qp_lnt',1,'The qpc.lnt option file'],['../ports_lint.html#lint_std_lnt',1,'The std.lnt option file']]],
  ['options_20for_20qp_20c_21',['Structure of PC-Lint-Plus Options for QP/C',['../ports_lint.html#lint_options',1,'']]],
  ['organization_22',['Organization',['../srs-qp.html#srs-qp_org',1,'Document Organization'],['../exa.html#exa_code',1,'Example Code Organization']]],
  ['orientation_23',['Object Orientation',['../index.html#over_oop',1,'']]],
  ['os2_24',['OS2',['../uc-os2.html#uc-os2_about',1,'About the QP/C Port to uC-OS2'],['../uc-os2.html',1,'uC-OS2']]],
  ['os2_20port_25',['Examples for the uC-OS2 Port',['../uc-os2.html#uc-os2_exa',1,'']]],
  ['os2_20source_20and_20arm_20cortex_20m3_20m4_20ports_26',['uC-OS2 Source and ARM Cortex-M3/M4 Ports',['../uc-os2.html#uc-os2_source',1,'']]],
  ['osal_27',['Active Object OSAL',['../sds-qp_ifc.html#sds-qp_osal-ao',1,'']]],
  ['oses_28',['Ports to General-Purpose OSes',['../ports_gpos.html',1,'ports']]],
  ['osobject_29',['osObject',['../struct_q_active.html#a6c548e60ddbedba9deb122a92449242c',1,'QActive']]],
  ['overview_30',['Overview',['../srs-qp_over.html',1,'Overview'],['../index.html',1,'Overview']]],
  ['own_20qp_20c_20projects_31',['Creating your Own QP/C Projects',['../exa.html#exa_own',1,'']]],
  ['ownership_20rules_32',['Mutable Event Ownership Rules',['../srs-qp_emm.html#srs-qp_emm-ownership',1,'']]]
];
