var searchData=
[
  ['c_0',['C',['../gs_get.html',1,'Downloading &amp;amp; Installing QP/C'],['../ports_lint.html#lint_options',1,'Structure of PC-Lint-Plus Options for QP/C']]],
  ['c_20application_20code_1',['Linting QP/C Application Code',['../ports_lint.html#lint_app',1,'']]],
  ['c_20as_20a_20cmsis_20pack_2',['Downloading QP/C as a CMSIS-Pack',['../gs_get.html#gs_pack',1,'']]],
  ['c_20from_20github_3',['Downloading QP/C from GitHub',['../gs_get.html#gs_gh',1,'']]],
  ['c_20in_20qp_20trade_20bundle_4',['Downloading QP/C in QP&amp;trade;-Bundle',['../gs_get.html#gs_bundle',1,'']]],
  ['c_20installation_20folder_5',['QP/C Installation Folder',['../gs_get.html#gs_dir',1,'']]],
  ['c_20port_6',['C Port',['../embos.html#embos_build',1,'QP/C Source Files Needed in this QP/C Port'],['../threadx.html#threadx_build',1,'QP/C Source Files Needed in this QP/C Port']]],
  ['c_20port_20to_20freertos_7',['About the QP/C Port to FreeRTOS',['../freertos.html#freertos_about',1,'']]],
  ['c_20port_20to_20uc_20os2_8',['About the QP/C Port to uC-OS2',['../uc-os2.html#uc-os2_about',1,'']]],
  ['c_20port_20to_20zephyr_9',['About the QP/C Port to Zephyr',['../zephyr.html#zephyr_about',1,'']]],
  ['c_20ports_20to_20arm_20cortex_20m_10',['Interrupts in the QP/C Ports to ARM Cortex-M',['../arm-cm.html#arm-cm_int',1,'']]],
  ['c_20projects_11',['Creating your Own QP/C Projects',['../exa.html#exa_own',1,'']]],
  ['c_20source_20code_12',['Linting the QP/C Source Code',['../ports_lint.html#lint_qp',1,'']]],
  ['c_20source_20files_20needed_20in_20this_20qp_20c_20port_13',['C Source Files Needed in this QP C Port',['../embos.html#embos_build',1,'QP/C Source Files Needed in this QP/C Port'],['../threadx.html#threadx_build',1,'QP/C Source Files Needed in this QP/C Port']]],
  ['c_20tutorial_14',['QP/C Tutorial',['../gs_tut.html',1,'gs']]],
  ['callback_20qk_20qxk_15',['The Idle Callback (QK/QXK)',['../tut_low.html#tut_low-idle',1,'']]],
  ['case_16',['Main Use Case',['../srs-qp_over.html#srs-qp_over-use',1,'']]],
  ['certificate_20file_17',['QP License Certificate File',['../gs_get.html#cert',1,'']]],
  ['channel_18',['QS-RX Receive Channel',['../srs-qp_qs.html#srs-qp_qs-rx',1,'']]],
  ['channel_20qs_20rx_19',['QS Receive-Channel (QS-RX)',['../api.html#api_qs_rx',1,'']]],
  ['char_5ft_20',['char_t',['../qpc_8h.html#a40bb5262bf908c328fbcfbe5d29d0201',1,'qpc.h']]],
  ['class_20view_21',['Class View',['../sds-qp_struct.html#sds-qp_cls',1,'']]],
  ['clock_20tick_22',['System Clock Tick',['../srs-qp_tm.html#srs-qp_tm-tick',1,'']]],
  ['closed_20source_20projects_23',['Closed Source Projects',['../index.html#over_closed-source',1,'']]],
  ['cmd_5foptions_2edox_24',['cmd_options.dox',['../cmd__options_8dox.html',1,'']]],
  ['cmsis_20pack_25',['Downloading QP/C as a CMSIS-Pack',['../gs_get.html#gs_pack',1,'']]],
  ['code_26',['Code',['../freertos.html#freertos_exa',1,'Example Code'],['../ports_lint.html#lint_app',1,'Linting QP/C Application Code'],['../ports_lint.html#lint_qp',1,'Linting the QP/C Source Code'],['../tut_low.html#tut_low-code',1,'The Low-Power Code'],['../exa.html#exa_sec_3rd',1,'Third-Party Code']]],
  ['code_20organization_27',['Example Code Organization',['../exa.html#exa_code',1,'']]],
  ['code_20structure_28',['Code Structure',['../ports.html#ports_code',1,'']]],
  ['comments_29',['Comments',['../ports.html#ports_gen',1,'General Comments'],['../exa.html#exa_gen',1,'General Comments']]],
  ['communication_30',['Asynchronous Communication',['../srs-qp_ao.html#srs-qp_ao-asynch',1,'']]],
  ['compile_20time_20configurability_31',['Compile-Time Configurability',['../srs-qp_over.html#srs-qp_conf_compile',1,'']]],
  ['compile_20time_20configuration_32',['Compile-Time Configuration',['../api.html#api_config',1,'']]],
  ['completion_20rtc_33',['Run-to-Completion (RTC)',['../srs-qp_ao.html#srs-qp_ao-rtc',1,'']]],
  ['completion_20rtc_20processing_34',['Run To Completion (RTC) Processing',['../srs-qp_sm.html#srs-qp_sm-rtc',1,'']]],
  ['complex_35',['SDS_QP_QHsm_tran-complex',['../sds-qp_alg.html#SDS_QP_QHsm_tran-complex',1,'']]],
  ['compliance_36',['Standards Compliance',['../srs-qp_nf.html#srs-qp_nf-sta',1,'']]],
  ['computation_37',['Active Object Model of Computation',['../srs-qp_ao.html#srs-qp_ao-model',1,'']]],
  ['concepts_20amp_20definitions_38',['Concepts amp Definitions',['../srs-qp_ao.html#srs-qp_ao-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_evt.html#srs-qp_evt-def',1,'Concepts &amp;amp; Definitions'],['../srs-qp_sm.html#srs-qp_sm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_edm.html#srs-qp_edm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_emm.html#srs-qp_emm-def',1,'Concepts &amp;amp; Definitions'],['../srs-qp_tm.html#srs-qp_tm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qs.html#srs-qp_qs-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qv.html#srs-qp_qv-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qk.html#srs-qp_qk-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qxk.html#srs-qp_qxk-intro',1,'Concepts &amp;amp; Definitions']]],
  ['concerns_39',['Concerns',['../sas-qp.html#sas-qp_conc',1,'Concerns'],['../sds-qp.html#sds-qp_conc',1,'Concerns']]],
  ['concurrency_40',['Encapsulation for Concurrency',['../srs-qp_ao.html#srs-qp_ao-enc',1,'']]],
  ['configurability_41',['Configurability',['../srs-qp_over.html#srs-qp_conf_compile',1,'Compile-Time Configurability'],['../srs-qp_over.html#srs-qp_over-conf',1,'Portability &amp;amp; Configurability'],['../srs-qp_over.html#srs-qp_conf_run',1,'Run-Time Configurability']]],
  ['configuration_42',['Compile-Time Configuration',['../api.html#api_config',1,'']]],
  ['configurations_43',['Build Configurations',['../exa.html#exa_sec_conf',1,'']]],
  ['constraints_44',['Constraints',['../srs-qp_nf.html#srs-qp_nf-con',1,'']]],
  ['contact_20information_45',['Contact Information',['../index.html#over_contact',1,'']]],
  ['context_46',['Execution Context',['../srs-qp_ao.html#srs-qp_ao-exec',1,'']]],
  ['context_20of_20use_47',['Context of Use',['../srs-qp_over.html#srs-qp_over-ctxt',1,'']]],
  ['context_20viewpoint_48',['Context Viewpoint',['../sas-qp_ctxt.html',1,'sas-qp']]],
  ['control_49',['Control',['../srs-qp_over.html#srs-qp_over_inv',1,'Inversion of Control'],['../srs-qp_ao.html#srs-qp_ao-inv',1,'Inversion of Control'],['../api.html#api_qv_init',1,'Kernel Initialization and Control'],['../api.html#api_qk_ctrl',1,'Kernel Initialization and Control'],['../api.html#api_qxk_ctrl',1,'Kernel Initialization and Control']]],
  ['conventions_50',['Conventions',['../srs-qp.html#srs-qp_conv',1,'Document Conventions'],['../sas-qp.html#sas-qp_conv',1,'Document Conventions'],['../sds-qp.html#sds-qp_conv',1,'Document Conventions']]],
  ['copy_20event_20management_51',['Zero-Copy Event Management',['../srs-qp_emm.html#srs-qp_emm-zero',1,'']]],
  ['cortex_20m_52',['Cortex M',['../arm-cm.html',1,'ARM Cortex-M'],['../arm-cm.html#arm-cm_int',1,'Interrupts in the QP/C Ports to ARM Cortex-M']]],
  ['cortex_20m3_20m4_20ports_53',['uC-OS2 Source and ARM Cortex-M3/M4 Ports',['../uc-os2.html#uc-os2_source',1,'']]],
  ['cortex_20r_54',['ARM Cortex-R',['../arm-cr.html',1,'ports_native']]],
  ['creating_20your_20own_20qp_20c_20projects_55',['Creating your Own QP/C Projects',['../exa.html#exa_own',1,'']]],
  ['crit_5fstat_5ft_56',['crit_stat_t',['../qp__port_8h.html#a4220a9f4183f80c82dadca3e438dac19',1,'qp_port.h']]],
  ['critentry_57',['critEntry',['../qp__port_8h.html#a22a7170380b1cbfb0f039b8d44d029f6',1,'qp_port.h']]],
  ['critexit_58',['critExit',['../qp__port_8h.html#a76ee9a87ef46f21dbca2d9046a4a50f4',1,'qp_port.h']]],
  ['critical_20section_59',['Critical Section',['../sds-qp_ifc.html#sds-qp_osal-cs',1,'']]],
  ['ctr_60',['ctr',['../struct_q_time_evt.html#a139b8ef35b103acac907b2aa14a00fc7',1,'QTimeEvt']]],
  ['current_20event_61',['Current Event',['../srs-qp_ao.html#srs-qp_ao-curr',1,'Current Event'],['../srs-qp_sm.html#srs-qp_sm-evt',1,'Current Event']]],
  ['current_20state_62',['Current State',['../srs-qp_sm.html#srs-qp_sm-curr',1,'']]]
];
