var searchData=
[
  ['dark_20mode_20toggle_0',['Dark Mode Toggle',['../help.html#help_dark_mode',1,'']]],
  ['data_1',['data',['../struct_q_s___t_probe.html#af62990111f1614c542e95efb6c6f5594',1,'QS_TProbe']]],
  ['data_20protocol_2',['Data Protocol',['../srs-qp_qs.html#srs-qp_qs-proto',1,'']]],
  ['dec_2027_202008_3',['Version 4.0.03, Dec 27, 2008',['../history.html#qpc_4_0_03',1,'']]],
  ['definitions_4',['Definitions',['../srs-qp_ao.html#srs-qp_ao-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_evt.html#srs-qp_evt-def',1,'Concepts &amp;amp; Definitions'],['../srs-qp_sm.html#srs-qp_sm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_edm.html#srs-qp_edm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_emm.html#srs-qp_emm-def',1,'Concepts &amp;amp; Definitions'],['../srs-qp_tm.html#srs-qp_tm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qs.html#srs-qp_qs-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qv.html#srs-qp_qv-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qk.html#srs-qp_qk-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qxk.html#srs-qp_qxk-intro',1,'Concepts &amp;amp; Definitions']]],
  ['delivery_20mechanisms_5',['Event Delivery Mechanisms',['../srs-qp_edm.html',1,'srs-qp']]],
  ['deprecated_20apis_6',['Deprecated APIs',['../deprecated.html',1,'']]],
  ['deriving_20application_20from_20a_20framework_7',['Deriving Application from a Framework',['../srs-qp_over.html#srs-qp_over-derive',1,'']]],
  ['design_20specification_8',['Software Design Specification',['../sds-qp.html',1,'']]],
  ['design_20specification_20uids_9',['Software-Design-Specification UIDs',['../sds-qp.html#sds-qp_uid',1,'']]],
  ['design_20view_10',['Design View',['../sds-qp_state.html#sds-qp_state-hsm',1,'QHsm Design View'],['../sds-qp_state.html#sds-qp_state-msm',1,'QMsm Design View']]],
  ['design_20viewpoints_11',['Design Viewpoints',['../sds-qp.html#sds-qp_vp',1,'']]],
  ['determinism_12',['Determinism',['../srs-qp_nf.html#srs-qp_nf-det',1,'']]],
  ['development_13',['Ease of Development',['../srs-qp_nf.html#srs-qp_nf-develop',1,'']]],
  ['development_20boards_14',['Development Boards',['../exa.html#exa_sec_boards',1,'']]],
  ['development_20tools_15',['Development Tools',['../exa.html#exa_sec_tools',1,'']]],
  ['dictionaries_16',['%QS Dictionaries',['../srs-qp_qs.html#srs-qp_qs-dict',1,'']]],
  ['dining_20philosophers_20problem_20dpp_17',['Dining Philosophers Problem (DPP)',['../tut_dpp.html',1,'gs_tut']]],
  ['dir_2edox_18',['dir.dox',['../dir_8dox.html',1,'']]],
  ['direct_20event_20posting_19',['Direct Event Posting',['../srs-qp_edm.html#srs-qp_edm-post',1,'']]],
  ['directories_20and_20files_20',['Directories and Files',['../arm-cm.html#arm-cm_files',1,'']]],
  ['dispatch_21',['dispatch',['../struct_q_asm_vtable.html#afac60b26d6a4222dc5078c5e06b2154e',1,'QAsmVtable']]],
  ['dispatching_20events_20to_20a_20state_20machine_22',['Dispatching Events to a State Machine',['../srs-qp_sm.html#srs-qp_sm-dispatch',1,'']]],
  ['do_23',['What does it do?',['../index.html#over_goals',1,'']]],
  ['document_20conventions_24',['Document Conventions',['../srs-qp.html#srs-qp_conv',1,'Document Conventions'],['../sas-qp.html#sas-qp_conv',1,'Document Conventions'],['../sds-qp.html#sds-qp_conv',1,'Document Conventions']]],
  ['document_20organization_25',['Document Organization',['../srs-qp.html#srs-qp_org',1,'']]],
  ['documentation_20traceability_26',['Documentation Traceability',['../index.html#over_tr',1,'']]],
  ['does_20it_20do_27',['What does it do?',['../index.html#over_goals',1,'']]],
  ['downloading_20amp_20installing_20qp_20c_28',['Downloading &amp;amp; Installing QP/C',['../gs_get.html',1,'gs']]],
  ['downloading_20qp_20c_20as_20a_20cmsis_20pack_29',['Downloading QP/C as a CMSIS-Pack',['../gs_get.html#gs_pack',1,'']]],
  ['downloading_20qp_20c_20from_20github_30',['Downloading QP/C from GitHub',['../gs_get.html#gs_gh',1,'']]],
  ['downloading_20qp_20c_20in_20qp_20trade_20bundle_31',['Downloading QP/C in QP&amp;trade;-Bundle',['../gs_get.html#gs_bundle',1,'']]],
  ['dpp_32',['Dining Philosophers Problem (DPP)',['../tut_dpp.html',1,'gs_tut']]],
  ['dual_20mode_20kernel_33',['Dual Mode Kernel',['../srs-qp_qxk.html',1,'Preemptive Dual-Mode Kernel'],['../api.html#api_qxk',1,'QXK (Dual-Mode Kernel)'],['../srs-qp_qxk.html#srs-qp_qxk-def',1,'QXK Dual-Mode Kernel']]],
  ['dual_20mode_20qxk_20kernel_34',['Preemptive &quot;Dual-Mode&quot; QXK Kernel',['../arm-cm_qxk.html',1,'arm-cm']]],
  ['dynamics_20viewpoint_35',['State Dynamics Viewpoint',['../sds-qp_state.html',1,'sds-qp']]]
];
