var searchData=
[
  ['idle_20callback_20qk_20qxk_0',['The Idle Callback (QK/QXK)',['../tut_low.html#tut_low-idle',1,'']]],
  ['idle_20processing_20in_20qk_1',['Idle Processing in QK',['../srs-qp_qk.html#srs-qp_qk-idle',1,'']]],
  ['idle_20processing_20in_20qv_2',['Idle Processing in QV',['../srs-qp_qv.html#srs-qp_qv-idle',1,'']]],
  ['idx_3',['idx',['../struct_q_s___t_probe.html#a53b9cba33f7a8aac5b7f3e7760b1e37d',1,'QS_TProbe']]],
  ['immutable_20events_4',['Immutable Events',['../srs-qp_emm.html#srs-qp_emm-imm',1,'']]],
  ['implementation_20strategy_5',['State Machine Implementation Strategy',['../srs-qp_sm.html#srs-qp_sm-impl',1,'']]],
  ['implementation_20view_6',['Implementation View',['../sds-qp_alg.html#sds-qp_qhsm',1,'QHsm Implementation View'],['../sds-qp_alg.html#sds-qp_qmsm',1,'QMsm Implementation View']]],
  ['in_20kernels_7',['in Kernels',['../index.html#over_kernels',1,'Built-in Kernels'],['../ports_native.html',1,'Native Ports (Built-in Kernels)']]],
  ['in_20qk_8',['in QK',['../srs-qp_qk.html#srs-qp_qk-idle',1,'Idle Processing in QK'],['../srs-qp_qk.html#srs-qp_qk-pre',1,'Preemptions in QK']]],
  ['in_20qp_20trade_20bundle_9',['Downloading QP/C in QP&amp;trade;-Bundle',['../gs_get.html#gs_bundle',1,'']]],
  ['in_20qv_10',['in QV',['../srs-qp_qv.html#srs-qp_qv-idle',1,'Idle Processing in QV'],['../srs-qp_qv.html#srs-qp_qv-share',1,'Sharing Resources in QV'],['../srs-qp_qv.html#srs-qp_qv-rt',1,'Task-Level Response in QV']]],
  ['in_20the_20qp_20c_20ports_20to_20arm_20cortex_20m_11',['Interrupts in the QP/C Ports to ARM Cortex-M',['../arm-cm.html#arm-cm_int',1,'']]],
  ['in_20this_20qp_20c_20port_12',['in this QP C Port',['../embos.html#embos_build',1,'QP/C Source Files Needed in this QP/C Port'],['../threadx.html#threadx_build',1,'QP/C Source Files Needed in this QP/C Port']]],
  ['information_13',['Contact Information',['../index.html#over_contact',1,'']]],
  ['init_14',['init',['../struct_q_asm_vtable.html#a0d43f4eb9172507649d322f03b901868',1,'QAsmVtable']]],
  ['initaction_15',['initAction',['../struct_q_m_state.html#ab9bc9157f2aa4ff022ec37937746217f',1,'QMState']]],
  ['initialization_20and_20control_16',['Initialization and Control',['../api.html#api_qv_init',1,'Kernel Initialization and Control'],['../api.html#api_qk_ctrl',1,'Kernel Initialization and Control'],['../api.html#api_qxk_ctrl',1,'Kernel Initialization and Control']]],
  ['initializing_20a_20state_20machine_17',['Initializing a State Machine',['../srs-qp_sm.html#srs-qp_sm-init',1,'']]],
  ['installation_20folder_18',['QP/C Installation Folder',['../gs_get.html#gs_dir',1,'']]],
  ['installing_20qp_20c_19',['Downloading &amp;amp; Installing QP/C',['../gs_get.html',1,'gs']]],
  ['int_5ft_20',['int_t',['../qp_8h.html#ab6fd6105e64ed14a0c9281326f05e623',1,'qp.h']]],
  ['interaction_20viewpoint_21',['Interaction Viewpoint',['../sds-qp_inter.html',1,'sds-qp']]],
  ['interest_22',['Quickly Locating a Topic of Interest',['../help.html#help_random',1,'']]],
  ['interface_20view_23',['Interface View',['../sas-qp_ctxt.html#sas-qp_ifc',1,'']]],
  ['interface_20viewpoint_24',['Interface Viewpoint',['../sds-qp_ifc.html',1,'sds-qp']]],
  ['interrupts_20in_20the_20qp_20c_20ports_20to_20arm_20cortex_20m_25',['Interrupts in the QP/C Ports to ARM Cortex-M',['../arm-cm.html#arm-cm_int',1,'']]],
  ['interval_26',['interval',['../struct_q_time_evt.html#a53b3919aabc87ac01af63c60e95ac35d',1,'QTimeEvt']]],
  ['intnest_27',['intNest',['../struct_q_k___attr.html#ac1eac87e193e60a0d1db967d6b688ecc',1,'QK_Attr']]],
  ['inversion_20of_20control_28',['Inversion of Control',['../srs-qp_over.html#srs-qp_over_inv',1,'Inversion of Control'],['../srs-qp_ao.html#srs-qp_ao-inv',1,'Inversion of Control']]],
  ['is_20it_29',['What is it?',['../index.html#over_about',1,'']]],
  ['is_20it_20licensed_30',['How is it licensed?',['../index.html#over_licensing',1,'']]],
  ['is_20software_20tracing_31',['What is Software Tracing?',['../srs-qp_qs.html#srs-qp_qs-set',1,'']]],
  ['isin_32',['isIn',['../struct_q_asm_vtable.html#a155dbbc0c15f8957c120011ad56b37de',1,'QAsmVtable']]],
  ['it_33',['it',['../index.html#over_about',1,'What is it?'],['../index.html#over_special',1,'What&apos;s special about it?']]],
  ['it_20do_34',['What does it do?',['../index.html#over_goals',1,'']]],
  ['it_20licensed_35',['How is it licensed?',['../index.html#over_licensing',1,'']]]
];
