var searchData=
[
  ['a_20cmsis_20pack_0',['Downloading QP/C as a CMSIS-Pack',['../gs_get.html#gs_pack',1,'']]],
  ['a_20framework_1',['Deriving Application from a Framework',['../srs-qp_over.html#srs-qp_over-derive',1,'']]],
  ['a_20library_2',['Framework, NOT a Library',['../srs-qp_over.html#srs-qp_over_frame',1,'']]],
  ['a_20state_20machine_3',['a State Machine',['../srs-qp_sm.html#srs-qp_sm-dispatch',1,'Dispatching Events to a State Machine'],['../srs-qp_sm.html#srs-qp_sm-init',1,'Initializing a State Machine']]],
  ['a_20topic_20of_20interest_4',['Quickly Locating a Topic of Interest',['../help.html#help_random',1,'']]],
  ['about_20it_5',['What&apos;s special about it?',['../index.html#over_special',1,'']]],
  ['about_20qp_20and_20qm_6',['Next Steps and Further Reading About QP and QM',['../exa.html#exa_doc',1,'']]],
  ['about_20the_20qp_20c_20port_20to_20freertos_7',['About the QP/C Port to FreeRTOS',['../freertos.html#freertos_about',1,'']]],
  ['about_20the_20qp_20c_20port_20to_20uc_20os2_8',['About the QP/C Port to uC-OS2',['../uc-os2.html#uc-os2_about',1,'']]],
  ['about_20the_20qp_20c_20port_20to_20zephyr_9',['About the QP/C Port to Zephyr',['../zephyr.html#zephyr_about',1,'']]],
  ['about_20the_20qp_20framework_20family_10',['About the %QP Framework Family',['../srs-qp.html#srs-qp_about',1,'']]],
  ['act_11',['act',['../struct_q_m_tran_act_table.html#a37933326f228b752952b1451375a32c2',1,'QMTranActTable::act'],['../union_q_asm_attr.html#afc8a07fdf9ec41798fb1e52fca43b767',1,'QAsmAttr::act'],['../struct_q_time_evt.html#aea7a53665e22ad00736ce3d013eed2eb',1,'QTimeEvt::act']]],
  ['active_20object_20model_20of_20computation_12',['Active Object Model of Computation',['../srs-qp_ao.html#srs-qp_ao-model',1,'']]],
  ['active_20object_20osal_13',['Active Object OSAL',['../sds-qp_ifc.html#sds-qp_osal-ao',1,'']]],
  ['active_20objects_14',['Active Objects',['../srs-qp_ao.html',1,'Active Objects'],['../srs-qp_ao.html#srs-qp_ao-def',1,'Active Objects'],['../api.html#api_ao',1,'Active Objects'],['../srs-qp_qs.html#srs-qp_qs-ao',1,'Software Tracing &amp;amp; Active Objects']]],
  ['actprio_15',['actPrio',['../struct_q_k___attr.html#a6ba1066c16fe4e8177b455a59402238e',1,'QK_Attr']]],
  ['actthre_16',['actThre',['../struct_q_k___attr.html#a6105aeefd1484f27d1b14bf4c06b4ae4',1,'QK_Attr']]],
  ['addr_17',['addr',['../struct_q_s___t_probe.html#a747c514bca735e5d7b211cb0ba73d3e6',1,'QS_TProbe']]],
  ['algorithm_20viewpoint_18',['Algorithm Viewpoint',['../sds-qp_alg.html',1,'sds-qp']]],
  ['amp_20active_20objects_19',['Software Tracing &amp;amp; Active Objects',['../srs-qp_qs.html#srs-qp_qs-ao',1,'']]],
  ['amp_20configurability_20',['Portability &amp;amp; Configurability',['../srs-qp_over.html#srs-qp_over-conf',1,'']]],
  ['amp_20definitions_21',['amp Definitions',['../srs-qp_ao.html#srs-qp_ao-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_evt.html#srs-qp_evt-def',1,'Concepts &amp;amp; Definitions'],['../srs-qp_sm.html#srs-qp_sm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_edm.html#srs-qp_edm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_emm.html#srs-qp_emm-def',1,'Concepts &amp;amp; Definitions'],['../srs-qp_tm.html#srs-qp_tm-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qs.html#srs-qp_qs-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qv.html#srs-qp_qv-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qk.html#srs-qp_qk-intro',1,'Concepts &amp;amp; Definitions'],['../srs-qp_qxk.html#srs-qp_qxk-intro',1,'Concepts &amp;amp; Definitions']]],
  ['amp_20installing_20qp_20c_22',['Downloading &amp;amp; Installing QP/C',['../gs_get.html',1,'gs']]],
  ['amp_20maturity_23',['Popularity &amp;amp; Maturity',['../index.html#over_popular',1,'']]],
  ['and_20arm_20cortex_20m3_20m4_20ports_24',['uC-OS2 Source and ARM Cortex-M3/M4 Ports',['../uc-os2.html#uc-os2_source',1,'']]],
  ['and_20control_25',['and Control',['../api.html#api_qv_init',1,'Kernel Initialization and Control'],['../api.html#api_qk_ctrl',1,'Kernel Initialization and Control'],['../api.html#api_qxk_ctrl',1,'Kernel Initialization and Control']]],
  ['and_20efficiency_26',['Size and Efficiency',['../index.html#over_eff',1,'']]],
  ['and_20files_27',['Directories and Files',['../arm-cm.html#arm-cm_files',1,'']]],
  ['and_20further_20reading_20about_20qp_20and_20qm_28',['Next Steps and Further Reading About QP and QM',['../exa.html#exa_doc',1,'']]],
  ['and_20qm_29',['Next Steps and Further Reading About QP and QM',['../exa.html#exa_doc',1,'']]],
  ['and_20scope_30',['and Scope',['../srs-qp.html#srs-qp_scope',1,'Purpose and Scope'],['../sas-qp.html#sas-qp_scope',1,'Purpose and Scope'],['../sds-qp.html#sds-qp_scope',1,'Purpose and Scope']]],
  ['api_20multithreaded_31',['Win32 API (Multithreaded)',['../win32.html',1,'ports_gpos']]],
  ['api_20reference_32',['API Reference',['../api.html',1,'']]],
  ['api_2edox_33',['api.dox',['../api_8dox.html',1,'']]],
  ['apis_34',['Deprecated APIs',['../deprecated.html',1,'']]],
  ['application_35',['Simple Blinky Application',['../tut_blinky.html',1,'gs_tut']]],
  ['application_20code_36',['Linting QP/C Application Code',['../ports_lint.html#lint_app',1,'']]],
  ['application_20from_20a_20framework_37',['Deriving Application from a Framework',['../srs-qp_over.html#srs-qp_over-derive',1,'']]],
  ['application_20specific_20trace_20records_38',['Application-Specific Trace Records',['../srs-qp_qs.html#srs-qp_qs-app',1,'']]],
  ['applications_39',['Example Applications',['../exa.html#exa_sec_apps',1,'']]],
  ['apr_2007_202008_40',['Version 4.0.00, Apr 07, 2008',['../history.html#qpc_4_0_00',1,'']]],
  ['apr_2009_202009_41',['Version 4.0.04, Apr 09, 2009',['../history.html#qpc_4_0_04',1,'']]],
  ['architectural_20viewpoints_42',['Architectural Viewpoints',['../sas-qp.html#sas-qp_vp',1,'']]],
  ['architecture_43',['Low Power Architecture',['../srs-qp_ao.html#srs-qp_ao-power',1,'']]],
  ['architecture_20specification_44',['Software Architecture Specification',['../sas-qp.html',1,'']]],
  ['architecture_20specification_20uids_45',['Architecture Specification UIDs',['../sas-qp.html#sas-qp_uid',1,'']]],
  ['arm_20cortex_20m_46',['ARM Cortex M',['../arm-cm.html',1,'ARM Cortex-M'],['../arm-cm.html#arm-cm_int',1,'Interrupts in the QP/C Ports to ARM Cortex-M']]],
  ['arm_20cortex_20m3_20m4_20ports_47',['uC-OS2 Source and ARM Cortex-M3/M4 Ports',['../uc-os2.html#uc-os2_source',1,'']]],
  ['arm_20cortex_20r_48',['ARM Cortex-R',['../arm-cr.html',1,'ports_native']]],
  ['as_20a_20cmsis_20pack_49',['Downloading QP/C as a CMSIS-Pack',['../gs_get.html#gs_pack',1,'']]],
  ['asynchronous_20communication_50',['Asynchronous Communication',['../srs-qp_ao.html#srs-qp_ao-asynch',1,'']]],
  ['audience_51',['Audience',['../srs-qp.html#srs-qp_audience',1,'']]],
  ['aug_2004_202012_52',['Version 4.5.02, Aug 04, 2012',['../history.html#qpc_4_5_02',1,'']]],
  ['aug_2013_202011_53',['Version 4.2.01, Aug 13, 2011',['../history.html#qpc_4_2_01',1,'']]],
  ['automatic_20event_20recycling_54',['Automatic Event Recycling',['../srs-qp_emm.html#srs-qp_emm-gc',1,'']]]
];
