var searchData=
[
  ['r_0',['ARM Cortex-R',['../arm-cr.html',1,'ports_native']]],
  ['rates_1',['Rates',['../tut_low.html#tut_low-tickrates',1,'Multiple Tick Rates'],['../srs-qp_tm.html#srs-qp_tm-rates',1,'Multiple Tick Rates']]],
  ['raw_20thread_20safe_2',['Event Queues (raw thread-safe)',['../api.html#api_queue',1,'']]],
  ['reading_20about_20qp_20and_20qm_3',['Next Steps and Further Reading About QP and QM',['../exa.html#exa_doc',1,'']]],
  ['reading_20online_20help_20sequentially_4',['Reading Online Help Sequentially',['../help.html#help_seq',1,'']]],
  ['readyset_5',['readySet',['../struct_q_k___attr.html#a1c45fe2c4a2445a557574e7a916faaaf',1,'QK_Attr::readySet'],['../struct_q_v___attr.html#a1c45fe2c4a2445a557574e7a916faaaf',1,'QV_Attr::readySet']]],
  ['receive_20channel_6',['QS-RX Receive Channel',['../srs-qp_qs.html#srs-qp_qs-rx',1,'']]],
  ['receive_20channel_20qs_20rx_7',['QS Receive-Channel (QS-RX)',['../api.html#api_qs_rx',1,'']]],
  ['records_8',['Records',['../srs-qp_qs.html#srs-qp_qs-app',1,'Application-Specific Trace Records'],['../srs-qp_qs.html#srs-qp_qs-pre',1,'Predefined Trace Records']]],
  ['recycling_9',['Automatic Event Recycling',['../srs-qp_emm.html#srs-qp_emm-gc',1,'']]],
  ['reentrancy_10',['Reentrancy',['../srs-qp_qs.html#srs-qp_qs-reent',1,'']]],
  ['refctr_5f_11',['refCtr_',['../struct_q_evt.html#a877dd7cab201e3fa2fe957ab36a18f2a',1,'QEvt']]],
  ['reference_12',['API Reference',['../api.html',1,'']]],
  ['references_13',['References',['../arm-cm.html#arm-cm_ref',1,'References'],['../srs-qp.html#srs-qp_ref',1,'References'],['../sas-qp.html#sas-qp_ref',1,'References'],['../sds-qp.html#sds-qp_ref',1,'References']]],
  ['requirement_20uids_14',['General Requirement UIDs',['../srs-qp.html#srs-qp_uid',1,'']]],
  ['requirements_15',['Requirements',['../srs-qp_nf.html',1,'Non-Functional Requirements'],['../srs-qp_ao.html#srs-qp_ao-req',1,'Requirements'],['../srs-qp_evt.html#srs-qp_evt-req',1,'Requirements'],['../srs-qp_sm.html#srs-qp_sm-req',1,'Requirements'],['../srs-qp_edm.html#srs-qp_edm-req',1,'Requirements'],['../srs-qp_emm.html#srs-qp_emm-req',1,'Requirements'],['../srs-qp_tm.html#srs-qp_tm-req',1,'Requirements'],['../srs-qp_qs.html#srs-qp_qs-req',1,'Requirements'],['../srs-qp_qv.html#srs-qp_qv-req',1,'Requirements'],['../srs-qp_qk.html#srs-qp_qk-req',1,'Requirements'],['../srs-qp_qxk.html#srs-qp_qxk-req',1,'Requirements']]],
  ['requirements_20specification_16',['Software Requirements Specification',['../srs-qp.html',1,'']]],
  ['resource_20viewpoint_17',['Resource Viewpoint',['../sas-qp_res.html',1,'sas-qp']]],
  ['resources_20in_20qv_18',['Sharing Resources in %QV',['../srs-qp_qv.html#srs-qp_qv-share',1,'']]],
  ['response_19',['Response',['../srs-qp_qk.html#srs-qp_qk-rt',1,'Task-Level Response'],['../srs-qp_qxk.html#srs-qp_qxk-rt',1,'Task-Level Response']]],
  ['response_20in_20qv_20',['Task-Level Response in %QV',['../srs-qp_qv.html#srs-qp_qv-rt',1,'']]],
  ['revision_20history_21',['Revision History',['../history.html',1,'']]],
  ['ring_22',['ring',['../struct_q_e_queue.html#a88978315c7e8e4f15e82250b7efe1617',1,'QEQueue']]],
  ['rtc_23',['Run-to-Completion (RTC)',['../srs-qp_ao.html#srs-qp_ao-rtc',1,'']]],
  ['rtc_20kernel_24',['QK (Preemptive RTC Kernel)',['../api.html#api_qk',1,'']]],
  ['rtc_20processing_25',['Run To Completion (RTC) Processing',['../srs-qp_sm.html#srs-qp_sm-rtc',1,'']]],
  ['rtos_26',['RTOS',['../exa.html#exa_rtos',1,'Examples for 3rd-party RTOS'],['../ports_rtos.html',1,'Ports to Third-Party RTOS']]],
  ['rules_27',['Mutable Event Ownership Rules',['../srs-qp_emm.html#srs-qp_emm-ownership',1,'']]],
  ['run_20time_20configurability_28',['Run-Time Configurability',['../srs-qp_over.html#srs-qp_conf_run',1,'']]],
  ['run_20time_20filtering_29',['Run-time Filtering',['../srs-qp_qs.html#srs-qp_qs-filter',1,'']]],
  ['run_20to_20completion_20rtc_30',['Run-to-Completion (RTC)',['../srs-qp_ao.html#srs-qp_ao-rtc',1,'']]],
  ['run_20to_20completion_20rtc_20processing_31',['Run To Completion (RTC) Processing',['../srs-qp_sm.html#srs-qp_sm-rtc',1,'']]],
  ['rx_32',['QS Receive-Channel (QS-RX)',['../api.html#api_qs_rx',1,'']]],
  ['rx_20receive_20channel_33',['QS-RX Receive Channel',['../srs-qp_qs.html#srs-qp_qs-rx',1,'']]]
];
