var searchData=
[
  ['m_0',['M',['../arm-cm.html',1,'ARM Cortex-M'],['../arm-cm.html#arm-cm_int',1,'Interrupts in the QP/C Ports to ARM Cortex-M']]],
  ['m3_20m4_20ports_1',['uC-OS2 Source and ARM Cortex-M3/M4 Ports',['../uc-os2.html#uc-os2_source',1,'']]],
  ['m4_20ports_2',['uC-OS2 Source and ARM Cortex-M3/M4 Ports',['../uc-os2.html#uc-os2_source',1,'']]],
  ['machine_3',['Machine',['../srs-qp_sm.html#srs-qp_sm-dispatch',1,'Dispatching Events to a State Machine'],['../srs-qp_sm.html#srs-qp_sm-hsm',1,'Hierarchical State Machine'],['../srs-qp_sm.html#srs-qp_sm-init',1,'Initializing a State Machine'],['../srs-qp_sm.html#srs-qp_sm-def',1,'State Machine']]],
  ['machine_20implementation_20strategy_4',['State Machine Implementation Strategy',['../srs-qp_sm.html#srs-qp_sm-impl',1,'']]],
  ['machine_20processor_5',['State Machine Processor',['../srs-qp_sm.html#srs-qp_sm-proc',1,'']]],
  ['machine_20specification_6',['State Machine Specification',['../srs-qp_sm.html#srs-qp_sm-spec',1,'']]],
  ['machines_7',['Machines',['../index.html#over_hsms',1,'Hierarchical State Machines'],['../srs-qp_sm.html',1,'State Machines'],['../tut_low.html#tut_low-sm',1,'State Machines'],['../api.html#api_hsm',1,'State Machines'],['../srs-qp_ao.html#srs-qp_ao-sm',1,'Support For State Machines']]],
  ['main_20use_20case_8',['Main Use Case',['../srs-qp_over.html#srs-qp_over-use',1,'']]],
  ['management_9',['Management',['../srs-qp_emm.html',1,'Event Memory Management'],['../api.html#api_mut',1,'Mutable Event Management'],['../srs-qp_tm.html',1,'Time Management'],['../api.html#api_time',1,'Time Management'],['../srs-qp_emm.html#srs-qp_emm-zero',1,'Zero-Copy Event Management']]],
  ['mar_2016_202010_10',['Version 4.1.04, Mar 16, 2010',['../history.html#qpc_4_1_04',1,'']]],
  ['mar_2023_202012_11',['Version 4.4.01, Mar 23, 2012',['../history.html#qpc_4_4_01',1,'']]],
  ['maturity_12',['Popularity &amp;amp; Maturity',['../index.html#over_popular',1,'']]],
  ['maxpool_5f_13',['maxPool_',['../struct_q_f___attr.html#a6fb3ff2b0cdd0735891a8ece515a6a48',1,'QF_Attr']]],
  ['may_14',['Use of &quot;may&quot;',['../srs-qp.html#srs-qp_conv-may',1,'']]],
  ['may_2029_202012_15',['Version 4.5.00, May 29, 2012',['../history.html#qpc_4_5_00',1,'']]],
  ['mechanisms_16',['Mechanisms',['../srs-qp_edm.html',1,'Event Delivery Mechanisms'],['../srs-qp_qxk.html#srs-qp_qxk-block',1,'QXK Blocking Mechanisms']]],
  ['memory_20management_17',['Event Memory Management',['../srs-qp_emm.html',1,'srs-qp']]],
  ['middleware_18',['Examples for 3rd-party Middleware',['../exa.html#exa_middleware',1,'']]],
  ['mode_19',['Mode',['../srs-qp_tm.html#srs-qp_tm-tickless',1,'&quot;Tickless Mode&quot;'],['../tut_low.html#tut_low-tickless',1,'The Tickless Mode']]],
  ['mode_20kernel_20',['Mode Kernel',['../srs-qp_qxk.html',1,'Preemptive Dual-Mode Kernel'],['../api.html#api_qxk',1,'QXK (Dual-Mode Kernel)'],['../srs-qp_qxk.html#srs-qp_qxk-def',1,'QXK Dual-Mode Kernel']]],
  ['mode_20qxk_20kernel_21',['Preemptive &quot;Dual-Mode&quot; QXK Kernel',['../arm-cm_qxk.html',1,'arm-cm']]],
  ['mode_20toggle_22',['Dark Mode Toggle',['../help.html#help_dark_mode',1,'']]],
  ['model_20of_20computation_23',['Active Object Model of Computation',['../srs-qp_ao.html#srs-qp_ao-model',1,'']]],
  ['models_24',['QM Models',['../exa.html#exa_sec_qm',1,'']]],
  ['msp430_25',['MSP430',['../msp430.html',1,'ports_native']]],
  ['multiple_20tick_20rates_26',['Multiple Tick Rates',['../tut_low.html#tut_low-tickrates',1,'Multiple Tick Rates'],['../srs-qp_tm.html#srs-qp_tm-rates',1,'Multiple Tick Rates']]],
  ['multithreaded_27',['Multithreaded',['../posix.html',1,'POSIX (Multithreaded)'],['../win32.html',1,'Win32 API (Multithreaded)']]],
  ['mutable_20event_20management_28',['Mutable Event Management',['../api.html#api_mut',1,'']]],
  ['mutable_20event_20ownership_20rules_29',['Mutable Event Ownership Rules',['../srs-qp_emm.html#srs-qp_emm-ownership',1,'']]],
  ['mutable_20events_30',['Mutable Events',['../srs-qp_emm.html#srs-qp_emm-mut',1,'']]]
];
